package dev.first.runnerz.cardio;

public enum Equipment {
    NONE,
    DUMBBELLS,
    BARBELL,
    CABLE_MACHINE,
    KETTLEBELL,
    RESISTANCE_BAND,
    BODYWEIGHT,
    BENCH,
    MEDICINE_BALL,
    TREADMILL,
    ELLIPTICAL,
    STAIRMASTER,
    ROWING_MACHINE,
    BIKE,
    JUMP_ROPE,
    SWIMMING_POOL,
    TRACK,
    FIELD,
    PULLUP_BAR,
    DIP_BAR,
    SLED,
    SLEDGEHAMMER,
    BATTLE_ROPE,
    SANDBAG,
    BOX,
    PLYO_BOX,
    RINGS,
    TRX,
    SLAM_BALL,
    WALL_BALL,
    ROWER
}
