### Find ALl Cardio Activities
GET http://localhost:8080/api/cardio/jdbc/AllCardio

### Find Cardio By ID
GET http://localhost:8080/api/cardio/jdbc/5


### Create new Cardio Activity
POST http://localhost:8080/api/cardio/jdbc
Content-Type: application/json

{
  "id": 11,
  "name": "Leg",
  "description": "targetting",
  "equipment": "KETTLEBELL",
  "targetMuscle": "pull",
  "difficulty": "High",
  "typee": "Gym"
}

### Create new Cardio Activity with invalid Equipment
POST http://localhost:8080/api/runs/jdbc
Content-Type: application/json

{
  "id": 5,
  "name": "Pull",
  "description": "targetting the lower back",
  "equipment": "barr",
  "targetMuscle": "Back",
  "difficulty": "High",
  "typee": "Gym"
}

### Update an existing Cardio Activity
PUT http://localhost:8080/api/cardio/jdbc/5
Content-Type: application/json

{
  "id": 5,
  "name": "LEG",
  "description": "targetting the lower back",
  "equipment": "KETTLEBELL",
  "targetMuscle": "Back",
  "difficulty": "High",
  "typee": "Gym"
}

### Delete a Cardio Activity
DELETE http://localhost:8080/api/cardio/jdbc/5